import { ParkingLot, HostBookingRequest } from './types';

export const INITIAL_PARKING_LOTS: ParkingLot[] = [
  {
    id: 'gulmohar-heights',
    name: 'Gulmohar Heights CHS',
    subTitle: 'Stilt Parking Level 0',
    type: 'residential',
    address: 'Gulmohar Cross Road 9, Near NMIMS Campus, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1031, 72.8372],
    hourlyRate: 40,
    totalBays: 16,
    availableBays: 2,
    clearance: '2.1m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Proceed to Gate 2. Inform security you have a Park Ryze reservation for Stilt Level 0.',
    entryGate: 'Gate 2 (West Wing)',
    hostName: 'Karan Mehra (Flat 402)',
    hostPhone: '+91 98201 44521',
    levelName: 'Stilt Level 0',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 EE 7812' },
      { id: 'A-03', row: 'A', number: 3, status: 'reserved', vehicleSize: 'suv' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'compact' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 04 BK 3390' },
      { id: 'A-06', row: 'A', number: 6, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 CD 5521' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 03 FL 9011' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 47 AH 2291' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 BW 9002' },
      { id: 'B-02', row: 'B', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 DD 1109' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'sedan' }, // Recommended Demo Slot
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 12 QX 4400' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 CN 7712' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 TR 1920' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 MP 8831' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 XZ 5102' },
    ],
  },
  {
    id: 'sea-breeze-bandra',
    name: 'Sea Breeze Co-Op Society',
    subTitle: 'Podium Level P1',
    type: 'residential',
    address: 'Zig Zag Road, Off Carter Road, Pali Hill, Bandra West, Mumbai',
    locality: 'Bandra West',
    coordinates: [19.0657, 72.8272],
    hourlyRate: 60,
    totalBays: 16,
    availableBays: 3,
    clearance: '2.4m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'RFID scanner at Main Gate. Show QR code pass on smartphone to security desk.',
    entryGate: 'Gate 1 (North Ramp)',
    hostName: 'Dr. Rohan Alva (Tower C)',
    hostPhone: '+91 98190 23114',
    levelName: 'Podium P1',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'suv' },
      { id: 'A-02', row: 'A', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 ZP 1234' },
      { id: 'A-04', row: 'A', number: 4, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 AB 9988' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 ER 4120' },
      { id: 'A-06', row: 'A', number: 6, status: 'reserved', vehicleSize: 'sedan' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 LK 7611' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 NM 3419' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 AA 8871' },
      { id: 'B-02', row: 'B', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 14 KL 5541' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 TT 2910' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 KK 3344' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 FF 8790' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 CV 6712' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 DD 9901' },
    ],
  },
  {
    id: 'maker-chambers-hub',
    name: 'Maker Chambers V Hub',
    subTitle: 'Commercial Smart Basement B2',
    type: 'commercial',
    address: 'Jamnalal Bajaj Road, Nariman Point, South Mumbai',
    locality: 'Nariman Point',
    coordinates: [18.9281, 72.8242],
    hourlyRate: 80,
    totalBays: 16,
    availableBays: 14,
    clearance: '2.2m Clearance',
    cctv: true,
    verifiedSociety: false,
    securityGateNotes: 'Automated Boom Barrier. Scan Park Ryze QR Pass at Entrance Sensor 1.',
    entryGate: 'East Express Ramp',
    hostName: 'Maker Commercial Facility Management',
    hostPhone: '+91 22 6678 9900',
    levelName: 'Basement B2',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-03', row: 'A', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'compact' },
      { id: 'A-05', row: 'A', number: 5, status: 'available', vehicleSize: 'compact' },
      { id: 'A-06', row: 'A', number: 6, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 01 BM 0007' },
      { id: 'A-08', row: 'A', number: 8, status: 'available', vehicleSize: 'compact' },
      { id: 'B-01', row: 'B', number: 1, status: 'available', vehicleSize: 'compact' },
      { id: 'B-02', row: 'B', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 RR 1111' },
      { id: 'B-05', row: 'B', number: 5, status: 'available', vehicleSize: 'compact' },
      { id: 'B-06', row: 'B', number: 6, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-07', row: 'B', number: 7, status: 'available', vehicleSize: 'suv' },
      { id: 'B-08', row: 'B', number: 8, status: 'available', vehicleSize: 'compact' },
    ],
  },
  {
    id: 'phoenix-palladium-mlcp',
    name: 'Phoenix Palladium MLCP',
    subTitle: 'Commercial MLCP Level 3',
    type: 'commercial',
    address: '462, Senapati Bapat Marg, Lower Parel, Mumbai',
    locality: 'Lower Parel',
    coordinates: [18.9953, 72.8245],
    hourlyRate: 70,
    totalBays: 16,
    availableBays: 11,
    clearance: '2.3m Clearance',
    cctv: true,
    verifiedSociety: false,
    securityGateNotes: 'Multi-Level Car Park entry via Senapati Bapat Marg ramp. Follow green digital signs.',
    entryGate: 'Ramp 3B (Grand Galleria Entry)',
    hostName: 'Palladium Parking Ops',
    hostPhone: '+91 22 4333 9999',
    levelName: 'MLCP Level 3',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'suv' },
      { id: 'A-02', row: 'A', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 JJ 4499' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 WW 3030' },
      { id: 'A-06', row: 'A', number: 6, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-07', row: 'A', number: 7, status: 'available', vehicleSize: 'compact' },
      { id: 'A-08', row: 'A', number: 8, status: 'available', vehicleSize: 'suv' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 47 KK 1212' },
      { id: 'B-02', row: 'B', number: 2, status: 'available', vehicleSize: 'compact' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 03 ZZ 9900' },
      { id: 'B-05', row: 'B', number: 5, status: 'available', vehicleSize: 'compact' },
      { id: 'B-06', row: 'B', number: 6, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 HH 6511' },
      { id: 'B-08', row: 'B', number: 8, status: 'available', vehicleSize: 'sedan' },
    ],
  },
  {
    id: 'hiranandani-heritage',
    name: 'Hiranandani Heritage CHS',
    subTitle: 'Covered Resident Bay',
    type: 'residential',
    address: 'Central Avenue, Hiranandani Gardens, Powai, Mumbai',
    locality: 'Powai',
    coordinates: [19.1197, 72.9051],
    hourlyRate: 50,
    totalBays: 16,
    availableBays: 4,
    clearance: '2.2m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Main Security Boom Barrier. Direct guard to notify Wing B resident pass.',
    entryGate: 'Kiosk 3 (Galleria Side)',
    hostName: 'Sunita Sharma (Tower Athena)',
    hostPhone: '+91 98331 87234',
    levelName: 'Ground Covered',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 03 BB 1100' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 FG 4521' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'compact' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 YY 8921' },
      { id: 'A-06', row: 'A', number: 6, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 UU 7611' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 QQ 3499' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 RR 8801' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 SS 9191' },
      { id: 'B-02', row: 'B', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 12 YY 3300' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 OO 4545' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 VV 1234' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 NN 9087' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 TT 6712' },
    ],
  },
  {
    id: 'silver-oak-chs',
    name: 'Silver Oak CHS',
    subTitle: 'Stilt Bay Level G',
    type: 'residential',
    address: 'Gulmohar Cross Road 7, JVPD Scheme, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1046, 72.8358],
    hourlyRate: 45,
    totalBays: 16,
    availableBays: 4,
    clearance: '2.2m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Entry from Gulmohar Cross Rd 7 gate. Show Park Ryze pass to guard; park in Stilt bay marked with green sensor.',
    entryGate: 'Gate 1 (Gulmohar 7 Wing)',
    hostName: 'Rajesh Singhania (Flat 601)',
    hostPhone: '+91 98203 11842',
    levelName: 'Stilt Ground Level',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 CZ 1042' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 BM 9912' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'compact' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 DX 4511' },
      { id: 'A-06', row: 'A', number: 6, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 BK 2201' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 EF 7710' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 AB 3412' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 GR 8821' },
      { id: 'B-02', row: 'B', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 14 HL 1928' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 JQ 6610' },
      { id: 'B-06', row: 'B', number: 6, status: 'reserved', vehicleSize: 'sedan' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 03 KP 5519' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 LN 3381' },
    ],
  },
  {
    id: 'ashoka-enclave-chs',
    name: 'Ashoka Enclave CHS',
    subTitle: 'Ground Stilt Parking',
    type: 'residential',
    address: 'V. L. Mehta Road, Opp NMIMS New Campus, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1039, 72.8351],
    hourlyRate: 50,
    totalBays: 16,
    availableBays: 2,
    clearance: '2.2m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Gate 1 on V. L. Mehta Road. Security desk verifies Park Ryze active QR token on arrival.',
    entryGate: 'Gate 1 (V. L. Mehta Road)',
    hostName: 'Sameer Parekh (Flat 703)',
    hostPhone: '+91 98205 99341',
    levelName: 'Stilt Level 0',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 AP 1120' },
      { id: 'A-02', row: 'A', number: 2, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 01 BG 9011' },
      { id: 'A-03', row: 'A', number: 3, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-04', row: 'A', number: 4, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 CN 7741' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 DL 5582' },
      { id: 'A-06', row: 'A', number: 6, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 ER 3319' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 FX 8890' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 GT 2211' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 HS 4492' },
      { id: 'B-02', row: 'B', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 JZ 1980' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 12 KQ 7720' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 LX 3310' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 MB 6614' },
      { id: 'B-07', row: 'B', number: 7, status: 'reserved', vehicleSize: 'compact' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 NC 9901' },
    ],
  },
  {
    id: 'vasant-vihar-chs',
    name: 'Vasant Vihar CHS',
    subTitle: 'Resident Podium P1',
    type: 'residential',
    address: '10th Road, JVPD Scheme, Near Mithibai College, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1022, 72.8394],
    hourlyRate: 50,
    totalBays: 16,
    availableBays: 5,
    clearance: '2.3m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Opposite Mithibai rear lane. Ramp leads directly to Podium P1. Present Park Ryze digital barcode.',
    entryGate: 'Podium Ramp 1A',
    hostName: 'Pradeep Merchant (Flat 502)',
    hostPhone: '+91 98214 78901',
    levelName: 'Podium Level P1',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'available', vehicleSize: 'suv' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 OP 4410' },
      { id: 'A-04', row: 'A', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 PQ 8821' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 03 QR 1290' },
      { id: 'A-06', row: 'A', number: 6, status: 'available', vehicleSize: 'compact' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 RS 6612' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 ST 9931' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 TU 5510' },
      { id: 'B-02', row: 'B', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 UV 2280' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 VW 7741' },
      { id: 'B-05', row: 'B', number: 5, status: 'available', vehicleSize: 'compact' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 WX 3390' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 XY 1122' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 YZ 8804' },
    ],
  },
  {
    id: 'sagar-villa-chs',
    name: 'Sagar Villa CHS',
    subTitle: 'Stilt Parking Level 0',
    type: 'residential',
    address: 'Gulmohar Cross Road 10, JVPD Scheme, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1051, 72.8392],
    hourlyRate: 40,
    totalBays: 16,
    availableBays: 5,
    clearance: '2.1m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Wide stilt entrance with dedicated visitor bay lane. Guard on duty at entrance booth.',
    entryGate: 'East Wing Gate 1',
    hostName: 'Nisha Kapadia (Flat 304)',
    hostPhone: '+91 98335 12099',
    levelName: 'Stilt Level 0',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'compact' },
      { id: 'A-02', row: 'A', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 ZA 7719' },
      { id: 'A-04', row: 'A', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 ZB 3320' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 ZC 9911' },
      { id: 'A-06', row: 'A', number: 6, status: 'available', vehicleSize: 'suv' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 04 ZD 4455' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 ZE 6610' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 ZF 1289' },
      { id: 'B-02', row: 'B', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 ZG 8830' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 03 ZH 5541' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 ZJ 2299' },
      { id: 'B-06', row: 'B', number: 6, status: 'available', vehicleSize: 'compact' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 ZK 7701' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 01 ZL 4432' },
    ],
  },
  {
    id: 'prarthana-heights-chs',
    name: 'Prarthana Heights CHS',
    subTitle: 'Podium Level P1',
    type: 'residential',
    address: 'Gulmohar Cross Road 5, Near Juhu Circle, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1015, 72.8348],
    hourlyRate: 45,
    totalBays: 16,
    availableBays: 3,
    clearance: '2.4m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Double security checkpoint. Ramp on south side leads to EV-ready covered bays.',
    entryGate: 'South Ramp Gate 2',
    hostName: 'Devang Shah (Flat 801)',
    hostPhone: '+91 98208 77112',
    levelName: 'Podium P1 (EV Capable)',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 AC 1928' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 BD 8831' },
      { id: 'A-04', row: 'A', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 CE 4410' },
      { id: 'A-05', row: 'A', number: 5, status: 'available', vehicleSize: 'suv' },
      { id: 'A-06', row: 'A', number: 6, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 DF 6620' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 EG 9901' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 01 FH 3345' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 GJ 7711' },
      { id: 'B-02', row: 'B', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 HK 2234' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 JL 5590' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 KM 1180' },
      { id: 'B-06', row: 'B', number: 6, status: 'reserved', vehicleSize: 'suv' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 LN 9940' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 MP 4422' },
    ],
  },
  {
    id: 'madhukunj-chs',
    name: 'Madhukunj CHS',
    subTitle: 'Covered Basement Level B1',
    type: 'residential',
    address: 'Gulmohar Cross Road 4, Near Kaifi Azmi Park, JVPD Scheme, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1054, 72.8341],
    hourlyRate: 40,
    totalBays: 16,
    availableBays: 3,
    clearance: '2.1m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Automated barrier at North Gate. Security registers vehicle plate at entry kiosk. Well-lit basement.',
    entryGate: 'North Gate (Park View)',
    hostName: 'Anita Desai (Flat 204)',
    hostPhone: '+91 98199 55420',
    levelName: 'Basement B1',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 NQ 3311' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 PR 7720' },
      { id: 'A-04', row: 'A', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 QS 9904' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 RT 4412' },
      { id: 'A-06', row: 'A', number: 6, status: 'available', vehicleSize: 'compact' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 SU 8890' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 TV 2231' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 UW 6670' },
      { id: 'B-02', row: 'B', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 VX 1140' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 WY 5520' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 XZ 9918' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 01 YA 3389' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 YB 7701' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 04 YC 4455' },
    ],
  },
  {
    id: 'palm-springs-chs',
    name: 'Palm Springs CHS',
    subTitle: 'Stilt Parking Level 0',
    type: 'residential',
    address: 'Gulmohar Cross Road 12, JVPD Scheme, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1068, 72.8383],
    hourlyRate: 35,
    totalBays: 16,
    availableBays: 6,
    clearance: '2.1m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Enter through Main Gate. Wide driveway with covered shade netting and 24/7 security guard.',
    entryGate: 'Main Society Gate',
    hostName: 'Vikram Kothari (Flat 301)',
    hostPhone: '+91 98332 66710',
    levelName: 'Covered Stilt Bay',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'available', vehicleSize: 'compact' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 YD 1920' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'suv' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 YE 8830' },
      { id: 'A-06', row: 'A', number: 6, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 YF 5541' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 04 YG 2210' },
      { id: 'A-08', row: 'A', number: 8, status: 'available', vehicleSize: 'compact' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 YH 9901' },
      { id: 'B-02', row: 'B', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 01 YJ 4418' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 YK 7729' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 YL 3390' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 YM 1182' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 YN 6640' },
    ],
  },
  {
    id: 'shanti-kunj-chs',
    name: 'Shanti Kunj CHS',
    subTitle: 'Covered Resident Bay',
    type: 'residential',
    address: 'N.S. Road No. 3, Near Cooper Hospital, JVPD Scheme, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1062, 72.8345],
    hourlyRate: 40,
    totalBays: 16,
    availableBays: 4,
    clearance: '2.0m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Quiet residential enclave. Stop at entry boom gate; resident society secretary pre-authorized guest parking.',
    entryGate: 'Gate B (Cooper Hospital Side)',
    hostName: 'Meera Choksi (Flat 102)',
    hostPhone: '+91 98191 44238',
    levelName: 'Ground Covered Stilt',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 YP 8812' },
      { id: 'A-03', row: 'A', number: 3, status: 'available', vehicleSize: 'compact' },
      { id: 'A-04', row: 'A', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 YQ 4430' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 YR 9921' },
      { id: 'A-06', row: 'A', number: 6, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 YS 3311' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 YT 7709' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 YU 2280' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 YV 5590' },
      { id: 'B-02', row: 'B', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 YW 1144' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 YX 6681' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 01 YY 3302' },
      { id: 'B-07', row: 'B', number: 7, status: 'reserved', vehicleSize: 'compact' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 YZ 8819' },
    ],
  },
];

export const INITIAL_HOST_REQUESTS: HostBookingRequest[] = [
  {
    id: 'req-01',
    driverName: 'Aditya Roy',
    bayId: 'B-42',
    tower: 'Tower B',
    vehiclePlate: 'MH 02 DW 8912',
    vehicleModel: 'Hyundai Creta',
    timeSlot: 'Today, 14:00 - 18:00',
    duration: '4 Hours',
    payout: 200,
    status: 'pending',
    receivedAt: '3 mins ago',
  },
  {
    id: 'req-02',
    driverName: 'Pooja Bhatt',
    bayId: 'A-12',
    tower: 'Tower A',
    vehiclePlate: 'MH 01 CE 3310',
    vehicleModel: 'Honda City',
    timeSlot: 'Today, 11:30 - 14:30',
    duration: '3 Hours',
    payout: 150,
    status: 'accepted',
    receivedAt: '45 mins ago',
  },
  {
    id: 'req-03',
    driverName: 'Vikram Joshi',
    bayId: 'B-18',
    tower: 'Tower B',
    vehiclePlate: 'MH 03 BT 4419',
    vehicleModel: 'Tata Nexon EV',
    timeSlot: 'Tomorrow, 09:00 - 17:00',
    duration: '8 Hours',
    payout: 400,
    status: 'pending',
    receivedAt: '12 mins ago',
  },
];
