import { ParkingLot, HostBookingRequest } from './types';

export const INITIAL_PARKING_LOTS: ParkingLot[] = [
  {
    id: 'gulmohar-heights',
    name: 'Gulmohar Heights CHS',
    subTitle: 'Stilt Parking Level 0',
    type: 'residential',
    address: 'Gulmohar Cross Road 9, Near NMIMS Campus, Vile Parle West, Mumbai',
    locality: 'Vile Parle West',
    coordinates: [19.1031, 72.8372],
    hourlyRate: 40,
    totalBays: 16,
    availableBays: 2,
    clearance: '2.1m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Proceed to Gate 2. Inform security you have a Park Ryze reservation for Stilt Level 0.',
    entryGate: 'Gate 2 (West Wing)',
    hostName: 'Karan Mehra (Flat 402)',
    hostPhone: '+91 98201 44521',
    levelName: 'Stilt Level 0',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 EE 7812' },
      { id: 'A-03', row: 'A', number: 3, status: 'reserved', vehicleSize: 'suv' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'compact' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 04 BK 3390' },
      { id: 'A-06', row: 'A', number: 6, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 CD 5521' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 03 FL 9011' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 47 AH 2291' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 BW 9002' },
      { id: 'B-02', row: 'B', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 DD 1109' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'sedan' }, // Recommended Demo Slot
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 12 QX 4400' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 CN 7712' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 TR 1920' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 MP 8831' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 XZ 5102' },
    ],
  },
  {
    id: 'sea-breeze-bandra',
    name: 'Sea Breeze Co-Op Society',
    subTitle: 'Podium Level P1',
    type: 'residential',
    address: 'Zig Zag Road, Off Carter Road, Pali Hill, Bandra West, Mumbai',
    locality: 'Bandra West',
    coordinates: [19.0657, 72.8272],
    hourlyRate: 60,
    totalBays: 16,
    availableBays: 3,
    clearance: '2.4m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'RFID scanner at Main Gate. Show QR code pass on smartphone to security desk.',
    entryGate: 'Gate 1 (North Ramp)',
    hostName: 'Dr. Rohan Alva (Tower C)',
    hostPhone: '+91 98190 23114',
    levelName: 'Podium P1',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'suv' },
      { id: 'A-02', row: 'A', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 ZP 1234' },
      { id: 'A-04', row: 'A', number: 4, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 AB 9988' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 ER 4120' },
      { id: 'A-06', row: 'A', number: 6, status: 'reserved', vehicleSize: 'sedan' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 LK 7611' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 NM 3419' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 AA 8871' },
      { id: 'B-02', row: 'B', number: 2, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 14 KL 5541' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 TT 2910' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 KK 3344' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 FF 8790' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 CV 6712' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 DD 9901' },
    ],
  },
  {
    id: 'maker-chambers-hub',
    name: 'Maker Chambers V Hub',
    subTitle: 'Commercial Smart Basement B2',
    type: 'commercial',
    address: 'Jamnalal Bajaj Road, Nariman Point, South Mumbai',
    locality: 'Nariman Point',
    coordinates: [18.9281, 72.8242],
    hourlyRate: 80,
    totalBays: 16,
    availableBays: 14,
    clearance: '2.2m Clearance',
    cctv: true,
    verifiedSociety: false,
    securityGateNotes: 'Automated Boom Barrier. Scan Park Ryze QR Pass at Entrance Sensor 1.',
    entryGate: 'East Express Ramp',
    hostName: 'Maker Commercial Facility Management',
    hostPhone: '+91 22 6678 9900',
    levelName: 'Basement B2',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-03', row: 'A', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'compact' },
      { id: 'A-05', row: 'A', number: 5, status: 'available', vehicleSize: 'compact' },
      { id: 'A-06', row: 'A', number: 6, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 01 BM 0007' },
      { id: 'A-08', row: 'A', number: 8, status: 'available', vehicleSize: 'compact' },
      { id: 'B-01', row: 'B', number: 1, status: 'available', vehicleSize: 'compact' },
      { id: 'B-02', row: 'B', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 RR 1111' },
      { id: 'B-05', row: 'B', number: 5, status: 'available', vehicleSize: 'compact' },
      { id: 'B-06', row: 'B', number: 6, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-07', row: 'B', number: 7, status: 'available', vehicleSize: 'suv' },
      { id: 'B-08', row: 'B', number: 8, status: 'available', vehicleSize: 'compact' },
    ],
  },
  {
    id: 'phoenix-palladium-mlcp',
    name: 'Phoenix Palladium MLCP',
    subTitle: 'Commercial MLCP Level 3',
    type: 'commercial',
    address: '462, Senapati Bapat Marg, Lower Parel, Mumbai',
    locality: 'Lower Parel',
    coordinates: [18.9953, 72.8245],
    hourlyRate: 70,
    totalBays: 16,
    availableBays: 11,
    clearance: '2.3m Clearance',
    cctv: true,
    verifiedSociety: false,
    securityGateNotes: 'Multi-Level Car Park entry via Senapati Bapat Marg ramp. Follow green digital signs.',
    entryGate: 'Ramp 3B (Grand Galleria Entry)',
    hostName: 'Palladium Parking Ops',
    hostPhone: '+91 22 4333 9999',
    levelName: 'MLCP Level 3',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'suv' },
      { id: 'A-02', row: 'A', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 JJ 4499' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 WW 3030' },
      { id: 'A-06', row: 'A', number: 6, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-07', row: 'A', number: 7, status: 'available', vehicleSize: 'compact' },
      { id: 'A-08', row: 'A', number: 8, status: 'available', vehicleSize: 'suv' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 47 KK 1212' },
      { id: 'B-02', row: 'B', number: 2, status: 'available', vehicleSize: 'compact' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 03 ZZ 9900' },
      { id: 'B-05', row: 'B', number: 5, status: 'available', vehicleSize: 'compact' },
      { id: 'B-06', row: 'B', number: 6, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 HH 6511' },
      { id: 'B-08', row: 'B', number: 8, status: 'available', vehicleSize: 'sedan' },
    ],
  },
  {
    id: 'hiranandani-heritage',
    name: 'Hiranandani Heritage CHS',
    subTitle: 'Covered Resident Bay',
    type: 'residential',
    address: 'Central Avenue, Hiranandani Gardens, Powai, Mumbai',
    locality: 'Powai',
    coordinates: [19.1197, 72.9051],
    hourlyRate: 50,
    totalBays: 16,
    availableBays: 4,
    clearance: '2.2m Clearance',
    cctv: true,
    verifiedSociety: true,
    securityGateNotes: 'Main Security Boom Barrier. Direct guard to notify Wing B resident pass.',
    entryGate: 'Kiosk 3 (Galleria Side)',
    hostName: 'Sunita Sharma (Tower Athena)',
    hostPhone: '+91 98331 87234',
    levelName: 'Ground Covered',
    supportedVehicles: ['car', 'two-wheeler'],
    bays: [
      { id: 'A-01', row: 'A', number: 1, status: 'available', vehicleSize: 'sedan' },
      { id: 'A-02', row: 'A', number: 2, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 03 BB 1100' },
      { id: 'A-03', row: 'A', number: 3, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 FG 4521' },
      { id: 'A-04', row: 'A', number: 4, status: 'available', vehicleSize: 'compact' },
      { id: 'A-05', row: 'A', number: 5, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 01 YY 8921' },
      { id: 'A-06', row: 'A', number: 6, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 04 UU 7611' },
      { id: 'A-07', row: 'A', number: 7, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 02 QQ 3499' },
      { id: 'A-08', row: 'A', number: 8, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 03 RR 8801' },
      { id: 'B-01', row: 'B', number: 1, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 02 SS 9191' },
      { id: 'B-02', row: 'B', number: 2, status: 'available', vehicleSize: 'sedan' },
      { id: 'B-03', row: 'B', number: 3, status: 'available', vehicleSize: 'suv' },
      { id: 'B-04', row: 'B', number: 4, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 12 YY 3300' },
      { id: 'B-05', row: 'B', number: 5, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 01 OO 4545' },
      { id: 'B-06', row: 'B', number: 6, status: 'occupied', vehicleSize: 'suv', occupiedPlate: 'MH 04 VV 1234' },
      { id: 'B-07', row: 'B', number: 7, status: 'occupied', vehicleSize: 'sedan', occupiedPlate: 'MH 02 NN 9087' },
      { id: 'B-08', row: 'B', number: 8, status: 'occupied', vehicleSize: 'compact', occupiedPlate: 'MH 03 TT 6712' },
    ],
  },
];

export const INITIAL_HOST_REQUESTS: HostBookingRequest[] = [
  {
    id: 'req-01',
    driverName: 'Aditya Roy',
    bayId: 'B-42',
    tower: 'Tower B',
    vehiclePlate: 'MH 02 DW 8912',
    vehicleModel: 'Hyundai Creta',
    timeSlot: 'Today, 14:00 - 18:00',
    duration: '4 Hours',
    payout: 200,
    status: 'pending',
    receivedAt: '3 mins ago',
  },
  {
    id: 'req-02',
    driverName: 'Pooja Bhatt',
    bayId: 'A-12',
    tower: 'Tower A',
    vehiclePlate: 'MH 01 CE 3310',
    vehicleModel: 'Honda City',
    timeSlot: 'Today, 11:30 - 14:30',
    duration: '3 Hours',
    payout: 150,
    status: 'accepted',
    receivedAt: '45 mins ago',
  },
  {
    id: 'req-03',
    driverName: 'Vikram Joshi',
    bayId: 'B-18',
    tower: 'Tower B',
    vehiclePlate: 'MH 03 BT 4419',
    vehicleModel: 'Tata Nexon EV',
    timeSlot: 'Tomorrow, 09:00 - 17:00',
    duration: '8 Hours',
    payout: 400,
    status: 'pending',
    receivedAt: '12 mins ago',
  },
];
